import { PresetTrajectory, BenchmarkMetrics } from "./types";

export const BENCHMARK_METRICS: BenchmarkMetrics[] = [
  {
    name: "Naive RAG (Baseline)",
    hallucination_rate: 0.50,
    precision: 0.50,
    verification_latency_ms: 0,
    gpu_vram_mb: 0,
    notes: "Direct LLM synthesis without post-hoc verification. Propagates subtle numerical & entity hallucinations.",
  },
  {
    name: "LLM-as-a-Judge (Prompted)",
    hallucination_rate: 0.375,
    precision: 0.625,
    verification_latency_ms: 4420,
    gpu_vram_mb: 12288,
    notes: "Secondary 12B LLM pass. Sycophantic to prior generation, suffers 4.4s latency and severe GPU VRAM contention.",
  },
  {
    name: "WARRANT Hybrid Verifier",
    hallucination_rate: 0.0,
    precision: 1.0,
    verification_latency_ms: 689,
    gpu_vram_mb: 0,
    notes: "Stage 1 Guard (<1ms) + Stage 2 Calibrated DeBERTa-v3 NLI on CPU. Zero GPU VRAM overhead, 0% hallucination rate.",
  },
];

export const PRESET_TRAJECTORIES: PresetTrajectory[] = [
  {
    id: "preset-1",
    title: "Arthur's Magazine vs First for Women",
    query: "Which magazine was started first, Arthur's Magazine or First for Women?",
    badge: "FULL_PASS",
    hopsRequired: 2,
    expectedDecision: "FULL_PASS",
    description: "Classic 2-hop temporal comparison requiring cross-document date attribution.",
    mockState: {
      query: "Which magazine was started first, Arthur's Magazine or First for Women?",
      current_hop: 2,
      max_hops: 2,
      retrieved_spans: [
        {
          id: "arthur_mag_s0",
          doc_title: "Arthur's Magazine",
          text: "Arthur's Magazine (1844–1846) was an American literary magazine published in Philadelphia in the 19th century.",
          char_start: 0,
          char_end: 110,
          retrieval_hop: 1,
          score: 0.942,
        },
        {
          id: "first_women_s0",
          doc_title: "First for Women",
          text: "First for Women is a woman's magazine published by Bauer Media Group in the USA.",
          char_start: 0,
          char_end: 80,
          retrieval_hop: 2,
          score: 0.918,
        },
        {
          id: "first_women_s1",
          doc_title: "First for Women",
          text: "The magazine was started in 1989 and is based in Englewood Cliffs, New Jersey.",
          char_start: 81,
          char_end: 159,
          retrieval_hop: 2,
          score: 0.956,
        },
      ],
      synthetic_claims: [
        {
          claim_id: "c_001",
          text: "Arthur's Magazine was founded in 1844.",
          cited_spans: ["arthur_mag_s0"],
          guard_status: "PASSED",
          guard_reasons: [],
          nli_label: "ENTAILMENT",
          nli_entailment_prob: 0.964,
          nli_neutral_prob: 0.026,
          nli_contradiction_prob: 0.010,
          nli_inference_latency_ms: 182,
          verification_status: "VERIFIED",
        },
        {
          claim_id: "c_002",
          text: "First for Women was started in 1989.",
          cited_spans: ["first_women_s1"],
          guard_status: "PASSED",
          guard_reasons: [],
          nli_label: "ENTAILMENT",
          nli_entailment_prob: 0.981,
          nli_neutral_prob: 0.012,
          nli_contradiction_prob: 0.007,
          nli_inference_latency_ms: 174,
          verification_status: "VERIFIED",
        },
      ],
      verified_claims: [
        {
          claim_id: "c_001",
          text: "Arthur's Magazine was founded in 1844.",
          cited_spans: ["arthur_mag_s0"],
          guard_status: "PASSED",
          guard_reasons: [],
          nli_label: "ENTAILMENT",
          nli_entailment_prob: 0.964,
          nli_neutral_prob: 0.026,
          nli_contradiction_prob: 0.010,
          nli_inference_latency_ms: 182,
          verification_status: "VERIFIED",
        },
        {
          claim_id: "c_002",
          text: "First for Women was started in 1989.",
          cited_spans: ["first_women_s1"],
          guard_status: "PASSED",
          guard_reasons: [],
          nli_label: "ENTAILMENT",
          nli_entailment_prob: 0.981,
          nli_neutral_prob: 0.012,
          nli_contradiction_prob: 0.007,
          nli_inference_latency_ms: 174,
          verification_status: "VERIFIED",
        },
      ],
      refuted_claims: [],
      unverifiable_claims: [],
      policy_decision: "FULL_PASS",
      policy_reason: "100% of synthetic claims (2/2) satisfy Stage 1 Guard and exceed calibrated DeBERTa NLI threshold (tau=0.82).",
      final_answer: "Arthur's Magazine was started first. Arthur's Magazine was founded in 1844, whereas First for Women was started later in 1989.",
      iteration: 1,
      retry_count: 0,
    },
  },
  {
    id: "preset-2",
    title: "Sinister & Scott Derrickson Nationality",
    query: "What is the nationality of the director of the film Sinister?",
    badge: "FULL_PASS",
    hopsRequired: 2,
    expectedDecision: "FULL_PASS",
    description: "Multi-hop entity resolution: Sinister -> Scott Derrickson -> American.",
    mockState: {
      query: "What is the nationality of the director of the film Sinister?",
      current_hop: 2,
      max_hops: 2,
      retrieved_spans: [
        {
          id: "sinister_s0",
          doc_title: "Sinister (film)",
          text: "Sinister is a 2012 supernatural horror film directed by Scott Derrickson and written by C. Robert Cargill and Derrickson.",
          char_start: 0,
          char_end: 122,
          retrieval_hop: 1,
          score: 0.965,
        },
        {
          id: "derrickson_s0",
          doc_title: "Scott Derrickson",
          text: "Scott Derrickson (born July 16, 1966) is an American filmmaker who lives in Los Angeles, California.",
          char_start: 0,
          char_end: 100,
          retrieval_hop: 2,
          score: 0.978,
        },
      ],
      synthetic_claims: [
        {
          claim_id: "c_101",
          text: "The film Sinister was directed by Scott Derrickson.",
          cited_spans: ["sinister_s0"],
          guard_status: "PASSED",
          guard_reasons: [],
          nli_label: "ENTAILMENT",
          nli_entailment_prob: 0.972,
          nli_neutral_prob: 0.019,
          nli_contradiction_prob: 0.009,
          nli_inference_latency_ms: 168,
          verification_status: "VERIFIED",
        },
        {
          claim_id: "c_102",
          text: "Scott Derrickson is an American filmmaker.",
          cited_spans: ["derrickson_s0"],
          guard_status: "PASSED",
          guard_reasons: [],
          nli_label: "ENTAILMENT",
          nli_entailment_prob: 0.988,
          nli_neutral_prob: 0.008,
          nli_contradiction_prob: 0.004,
          nli_inference_latency_ms: 161,
          verification_status: "VERIFIED",
        },
      ],
      verified_claims: [
        {
          claim_id: "c_101",
          text: "The film Sinister was directed by Scott Derrickson.",
          cited_spans: ["sinister_s0"],
          guard_status: "PASSED",
          guard_reasons: [],
          nli_label: "ENTAILMENT",
          nli_entailment_prob: 0.972,
          nli_neutral_prob: 0.019,
          nli_contradiction_prob: 0.009,
          nli_inference_latency_ms: 168,
          verification_status: "VERIFIED",
        },
        {
          claim_id: "c_102",
          text: "Scott Derrickson is an American filmmaker.",
          cited_spans: ["derrickson_s0"],
          guard_status: "PASSED",
          guard_reasons: [],
          nli_label: "ENTAILMENT",
          nli_entailment_prob: 0.988,
          nli_neutral_prob: 0.008,
          nli_contradiction_prob: 0.004,
          nli_inference_latency_ms: 161,
          verification_status: "VERIFIED",
        },
      ],
      refuted_claims: [],
      unverifiable_claims: [],
      policy_decision: "FULL_PASS",
      policy_reason: "Both entity-bridged claims verified with high entailment certainty (mean prob=0.980).",
      final_answer: "The director of the film Sinister is Scott Derrickson, who is American.",
      iteration: 1,
      retry_count: 0,
    },
  },
  {
    id: "preset-3",
    title: "Numerical Guard Triggered (Graceful Recovery)",
    query: "When was the creator of The Twilight Zone born and when was his final interview?",
    badge: "PARTIAL_PASS",
    hopsRequired: 2,
    expectedDecision: "PARTIAL_PASS",
    description: "One claim is fully verified, but an ungrounded hallucinated year triggers the Stage 1 Guard.",
    mockState: {
      query: "When was the creator of The Twilight Zone born and when was his final interview?",
      current_hop: 2,
      max_hops: 2,
      retrieved_spans: [
        {
          id: "serling_s0",
          doc_title: "Rod Serling",
          text: "Rodman Edward Serling (December 25, 1924 – June 28, 1975) was an American screenwriter and creator of The Twilight Zone.",
          char_start: 0,
          char_end: 120,
          retrieval_hop: 1,
          score: 0.961,
        },
      ],
      synthetic_claims: [
        {
          claim_id: "c_201",
          text: "Rod Serling was born on December 25, 1924.",
          cited_spans: ["serling_s0"],
          guard_status: "PASSED",
          guard_reasons: [],
          nli_label: "ENTAILMENT",
          nli_entailment_prob: 0.959,
          nli_neutral_prob: 0.028,
          nli_contradiction_prob: 0.013,
          nli_inference_latency_ms: 177,
          verification_status: "VERIFIED",
        },
        {
          claim_id: "c_202",
          text: "Rod Serling gave his final recorded interview in 1976.",
          cited_spans: ["serling_s0"],
          guard_status: "FAILED_NUMERICAL",
          guard_reasons: ["Hallucinated numeral '1976' not present in supporting span."],
          nli_label: "CONTRADICTION",
          nli_entailment_prob: 0.041,
          nli_neutral_prob: 0.120,
          nli_contradiction_prob: 0.839,
          nli_inference_latency_ms: 185,
          verification_status: "REFUTED",
        },
      ],
      verified_claims: [
        {
          claim_id: "c_201",
          text: "Rod Serling was born on December 25, 1924.",
          cited_spans: ["serling_s0"],
          guard_status: "PASSED",
          guard_reasons: [],
          nli_label: "ENTAILMENT",
          nli_entailment_prob: 0.959,
          nli_neutral_prob: 0.028,
          nli_contradiction_prob: 0.013,
          nli_inference_latency_ms: 177,
          verification_status: "VERIFIED",
        },
      ],
      refuted_claims: [
        {
          claim_id: "c_202",
          text: "Rod Serling gave his final recorded interview in 1976.",
          cited_spans: ["serling_s0"],
          guard_status: "FAILED_NUMERICAL",
          guard_reasons: ["Hallucinated numeral '1976' not present in supporting span."],
          nli_label: "CONTRADICTION",
          nli_entailment_prob: 0.041,
          nli_neutral_prob: 0.120,
          nli_contradiction_prob: 0.839,
          nli_inference_latency_ms: 185,
          verification_status: "REFUTED",
        },
      ],
      unverifiable_claims: [],
      policy_decision: "PARTIAL_PASS",
      policy_reason: "1 of 2 claims failed attribution. Refuted claim c_202 pruned to prevent hallucination propagation.",
      final_answer: "Rod Serling was born on December 25, 1924. [Note: Information regarding his final interview was omitted due to verification failure].",
      iteration: 2,
      retry_count: 1,
    },
  },
  {
    id: "preset-4",
    title: "Adversarial Hallucination / Zero Grounding (Strict Abstention)",
    query: "What quantum particle was discovered at the University of Toronto in 1782?",
    badge: "ABSTAIN",
    hopsRequired: 2,
    expectedDecision: "ABSTAIN",
    description: "Adversarial historical anachronism. Zero valid spans retrieved -> strict abstention refusal contract.",
    mockState: {
      query: "What quantum particle was discovered at the University of Toronto in 1782?",
      current_hop: 2,
      max_hops: 2,
      retrieved_spans: [],
      synthetic_claims: [],
      verified_claims: [],
      refuted_claims: [],
      unverifiable_claims: [],
      policy_decision: "ABSTAIN",
      policy_reason: "Zero supporting evidence spans retrieved for the premise. Strict 3-state abstention contract activated.",
      final_answer: "I am unable to answer this inquiry with warranted attribution. No verifiable historical evidence confirms quantum particle discoveries at the University of Toronto in 1782.",
      iteration: 2,
      retry_count: 2,
    },
  },
];
